"""Add auction table

Revision ID: 0b2378c1a239
Revises: b529e94ebb0d
Create Date: 2026-08-07 15:55:59.325981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b2378c1a239'
down_revision = 'b529e94ebb0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auctions',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('winner_customer_id', sa.Integer(), nullable=False),
    sa.Column('auction_month', sa.Integer(), nullable=False),
    sa.Column('auction_date', sa.Date(), nullable=False),
    sa.Column('bid_amount', sa.Float(), nullable=False),
    sa.Column('commission_amount', sa.Float(), nullable=False),
    sa.Column('net_bid_amount', sa.Float(), nullable=False),
    sa.Column('installment_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['chit_groups.id'], ),
    sa.ForeignKeyConstraint(['winner_customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auctions')
    # ### end Alembic commands ###
